### ISSUE TITLE
AttributeError: 'GotoolsFormat' object has no attribute 'runner'

### ISSUE THREAD

**Issue by tamird** [ironcladlou/GoTools#115]
Something was missed in https://github.com/ironcladlou/GoTools/commit/6b7b4574751b8a019274241fcf76358c79774b65#diff-1f0a2492cefa677ed49faf6317c4fda3R48

**Comment by ironcladlou** [comment]
Fixed in `0.1.7.1`.

**Comment by tamird** [comment]
Can you push `0.17.1` to packagecontrol?

**Comment by ironcladlou** [comment]
I already pushed the tag to GitHub- I'm not sure why Package Control isn't picking it up. This is the first time I've had any trouble.

**Comment by ironcladlou** [comment]
I pushed it as 0.1.8 instead. Apparently 0.1.7.1 doesn't comform to semantic versioning.
