### ISSUE TITLE
String formatting '%[d]s' (explicit argument indexes) syntax: highlighting broken

### ISSUE THREAD

**Issue by alecdwm** [ironcladlou/GoTools#119]
When using the Go fmt package one has the option to format a string with 'explicit argument indexes'.
(https://golang.org/pkg/fmt/): _ctrl+f search 'Explicit argument indexes:'_

The syntax highlighting for a string using this feature is incorrect, displaying the '%' character in the same formatting as an erroneous usage of the '%' character, rather than the formatting for the correct usage.

![image](https://cloud.githubusercontent.com/assets/2741569/10444932/22f9cb6a-71af-11e5-9576-ec367846c505.png)

**Comment by stevekuznetsov** [comment]
This is an upstream issue here: https://github.com/sublimehq/Packages/issues/48

It doesn't look like Sublime wants to maintain the syntax highlighting packages...

**Comment by alecdwm** [comment]
Ah no worries! Thanks! :+1:

**Comment by stevekuznetsov** [comment]
No problem, maybe if you go upstream and post your support for fixing that issue something will happen? I'm not hopeful, maybe I'll learn the new syntax language and do it myself soon.
