### ISSUE TITLE
A small suggestion：Put "go to definition" into right-mouse's menu

### ISSUE THREAD

**Issue by liuhewei** [ironcladlou/GoTools#123]
It's very common on other IDEs. Just put into [Context.sublime-menu](https://github.com/ironcladlou/GoTools/blob/master/Context.sublime-menu)
```
  {
    "command": "gotools_goto_def",
    "caption": "Go to definition"
  },
```

**Comment by ironcladlou** [comment]
FWIW, you can override the context menu of any plugin (including GoTools) by making a file which overwrites the plugin's context menu. For GoTools, create `$SUBLIME_CONFIG_DIR/Packages/GoTools/Context.sublime-menu` and modify as you prefer. I use this technique for the GitHubinator plugin to reduce the context entries to the two I use most.

**Comment by liuhewei** [comment]
@ironcladlou Thanks for the tips!

**Comment by ironcladlou** [comment]
Closing this since I don't intend to add the context menu item.
