### ISSUE TITLE
Test at cursor can sometimes match multiple test functions

### ISSUE THREAD

**Issue by ironcladlou** [ironcladlou/GoTools#47]
Consider a single test file with two test functions like:

```go
func Test_foo(t *testing.T) {}
func Test_foobar(t *testing.T) {}
```

If "Run test at cursor" is called within `Test_foo`, the `go test` execution will have args like `-run Test_foo` which will end up matching both `Test_foo` and `Test_foobar`. The user's intent is to run only `Test_foo`.

**Comment by pmorie** [comment]
I actually enjoy this behavior, it's been really convenient at certain points.

**Comment by ironcladlou** [comment]
I still think it's surprising behavior... when I say "Run test at cursor," I expect that test (and only that test) to run

**Comment by ironcladlou** [comment]
Sorry @pmorie, it's a BUG
