### ISSUE TITLE
Integrate with the Delve debugger

### ISSUE THREAD

**Issue by ironcladlou** [ironcladlou/GoTools#48]
Provide [Delve](https://github.com/derekparker/delve) debugger integration using the [upcoming HTTP API](https://github.com/derekparker/delve/pull/88).

SublimeText debugger integration inspiration:

* https://github.com/martomo/SublimeTextXdebug
* https://github.com/shuky19/sublime_debugger

**Comment by ironcladlou** [comment]
@pmorie 

We should discuss whether to add this integration to GoTools or to a separate plugin. Here's a feature I can imagine which would benefit from the integration being a part of GoTools:

* Debug test at cursor: uses the build system support to compile a test binary whose entrypoint is the test at the cursor, starts a debugging session
* Debug program: similar to debug at cursor, but uses the build system support to compile the main package as usual and starts a debugging session against the specified binary

**Comment by pmorie** [comment]
@ironcladlou Did we not say that (2) was actually attach to running program?

We also talked about run profiles like IDEs have, but I'm not sure we felt strongly about it if you have debug test and attach to program.

**Comment by ironcladlou** [comment]
I have a WIP branch going here: https://github.com/ironcladlou/GoTools/tree/delve

**Comment by ironcladlou** [comment]
I've decided this is way outside the scope of what Sublime can reasonably provide. Try Visual Studio Code with vscode-go for integrated debugging support.
