### ISSUE TITLE
Parity for build scripts and GOPATH build

### ISSUE THREAD

**Issue by pmorie** [ironcladlou/GoTools#49]
I want to be able to build via a build script (`hack/build-go.sh`) instead of doing a GOPATH build.  If my script prints output from the go compiler, I should be able to go to lines, etc, just as I would if I was running the go compiler directly.

**Comment by ironcladlou** [comment]
I wonder if this could result in confusing effects with gocode, oracle, or any other GOPATH based tool. If the build worked relative to some other GOPATH not matching the GoTools setting, the tools results could be incorrect.

**Comment by pmorie** [comment]
Hrm, good point.  Maybe there is some way to do both or reconcile the two.

**Comment by pmorie** [comment]
@ironcladlou I had an idea:

1.  Allow an optional build script to be specified and working dir to run it from.
2.  Run the GOPATH build first, if it succeeds, run the build script.

**Comment by ironcladlou** [comment]
I think I've decided I don't want to introduce this right now, and am going to just stick with integrating with the Go tooling. I wouldn't be opposed to a new proposal in the form of a PR for review. I'm going to close the issue since I personally have no intention of implementing.
