### ISSUE TITLE
GoImports -s flag is not supported

### ISSUE THREAD

**Issue by stevekuznetsov** [ironcladlou/GoTools#52]
The `-s` flag passed in [here](https://github.com/ironcladlou/GoTools/blob/master/GoTools.py#L290) is not supported for goimports.

**Comment by ironcladlou** [comment]
The `gofmt_cmd` setting should be more generalized to allow a command array (which includes args).

**Comment by ironcladlou** [comment]
Though that's a little dangerous. Allowing the user to supply *all* the args would give them rope to break the feature. For example, by adding something like `-w` to gofmt.

Would need to be well documented.
