### ISSUE TITLE
Syntax Highlighting bugs

### ISSUE THREAD

**Issue by stevekuznetsov** [ironcladlou/GoTools#59]
When using string formatting constructs like `%[1]s` instead of `%s`, syntax highlighting is broken: 
![screenshot from 2015-06-26 10 12 48](https://cloud.githubusercontent.com/assets/7328370/8379136/f59316f4-1beb-11e5-8688-174a7348d3b0.png)
--
If the method is defined all on one line, highlighting for the *method name* works fine but things like primitive types (`string`, `map`, *etc*) are not highlighted correctly: 
![screenshot from 2015-06-29 14 59 08](https://cloud.githubusercontent.com/assets/7328370/8415842/7ad53204-1e6f-11e5-98ed-0c76704ece81.png)
If there is a newline in the method definition, the *name* is not highlighted correctly, but the primitive types *are*:
![screenshot from 2015-06-29 14 59 33](https://cloud.githubusercontent.com/assets/7328370/8415841/7ad3cc70-1e6f-11e5-9011-d284a73d9d21.png)
--
With a leading `type` that is a `func`, I do not get the correct syntax highlighting on the `type` or the following method `func` or name: 
![nothing](https://cloud.githubusercontent.com/assets/7328370/8415152/d8242bcc-1e6a-11e5-92bb-3dd7be5a9d44.png)

With a leading function definition that is not finished, I get correct highlighting on the method `func` and name, but not on the `type` or the `func` in the typedef:
![leadingfunc](https://cloud.githubusercontent.com/assets/7328370/8415151/d821d70a-1e6a-11e5-9236-486ba9081a2e.png)

With the leading function braces closed, I get the same results as with no leading function:
![braceclosed](https://cloud.githubusercontent.com/assets/7328370/8415149/d81eccae-1e6a-11e5-95a0-ce6c9323bf44.png)

**Comment by ironcladlou** [comment]
The syntax highlighting should be converted to use Sublime's [new syntax format](https://www.sublimetext.com/docs/3/syntax.html), and we should scrap the tmLanguage stuff.

**Comment by stevekuznetsov** [comment]
Somehow it looks like you should support it [already](https://github.com/ironcladlou/GoTools/blob/master/GoTools.tmLanguage#L627) unless I am not understanding that regex correctly.

**Comment by ironcladlou** [comment]
@stevekuznetsov would you mind moving #70 and #71 into this issue and then closing them? I like your idea to have a single syntax issue.

**Comment by stevekuznetsov** [comment]
@ironcladlou Should have done that from the outset. my bad!

**Comment by stevekuznetsov** [comment]
Pushed this [upstream](https://github.com/sublimehq/Packages/issues/48)
