### ISSUE TITLE
Push syntax highlighting upstream?

### ISSUE THREAD

**Issue by ottob** [ironcladlou/GoTools#72]
Syntax packages for latest ST3 dev builds are now on Github: https://github.com/sublimehq/Packages

Also see https://github.com/DisposaBoy/GoSublime/issues/634

**Comment by ironcladlou** [comment]
I would definitely prefer to ditch the tmLanguage file here and just use the upstream sublime-syntax support.

**Comment by stevekuznetsov** [comment]
@ottob  @ironcladlou  I think this is a great idea - had no idea they were rolling out their implementations for us to use. I'll pull this into my fork and play with it. If it's an improvement, wohoo!

**Comment by stevekuznetsov** [comment]
Their implementation is  worse somehow - while we have (broken) syntax highlighting for string formatting anchors in grave accent (``` ` ```) strings, they don't have any... and all the other bugs are still present. Nevertheless I agree that GoTools doesn't need to support it's own version if we can use that one.

**Comment by stevekuznetsov** [comment]
@ironcladlou I think we can close this issue.

**Comment by ironcladlou** [comment]
I'm closing this because:

1. It's not clear to me whether what I'm already using here is better than what's upstream
2. I have no intentions of creating a new syntax file in the near future (despite the minor bugs with the existing syntax support)
3. I'm not clear on the workflow/process I'd need to establish to work with ST upstream if I were to adopt the upstream syntax file in GoTools

I don't have the time to address those points and move this forward, and will open a future issue if I (or a contributor) decide to take it on.

**Comment by stevekuznetsov** [comment]
For what it's worth, upstream seen to have converted the original syntax
highlighting to the new format but are not supporting it or making updates.
Upstream bash is even worse.

**Comment by ottob** [comment]
Upstream lives! :smile: 

Is it time to reconsider this? Go from build 3100 works better than the syntax highlighting included in GoTools .

**Comment by stevekuznetsov** [comment]
Absolutely. They're finally working on updating their highlighting, so I think GoTools no longer needs to support its own. @ironcladlou thoughts?

**Comment by ironcladlou** [comment]
No real objections... Don't count on me getting to it any time soon though. I'm still considering a full switch to VScode for go programming, and that has really took the wind out of my GoTools sails. 

Sublime finally released a pretty lackluster update today, which didn't help with my enthusiasm levels.

**Comment by ottob** [comment]
I didn't know VScode was worth a try, thanks for the hint.
