### ISSUE TITLE
OSX installation problems

### ISSUE THREAD

**Issue by ottob** [ironcladlou/GoTools#73]
The PATH environment variable handling for GUI applications seem [impossible](http://stackoverflow.com/questions/25385934/setting-environment-variables-via-launchd-conf-no-longer-works-in-os-x-yosemite#comment43575294_25912736) to get right with Yosemite (I'm running 10.10.4). So when ST is not launched from a terminal where it inherits the PATH environment it will get the default `/usr/bin:/bin:/usr/sbin:/sbin` and GoTools will not find the go tool.
```
File "/Users/myaccount/Library/Application Support/Sublime Text 3/Packages/GoTools/GoTools.py", line 30, in load_goenv
    raise Exception("GoTools: couldn't find the go binary in PATH: " + ospath)
Exception: GoTools: couldn't find the go binary in PATH: /usr/bin:/bin:/usr/sbin:/sbin
```
If I install https://github.com/int3h/SublimeFixMacPath and then edit GoTools.py forcing a reload, GoTool will find the go application. I have installed go via homebrew so it's in `/usr/local/bin`.
```
GoTools: initializing using Go binary: /usr/local/bin/go
```
But if I reload ST, GoTools sometimes fails. Maybe its a plugin load order issue so SublimeFixMacPath has not yet been able to fix the PATH variable. The only way I could get it working consistently is to modify GoTools.py:19 to `ospath = '/usr/local/bin'`.

I can't really see any good[1] way of solving this, but perhaps you have some idea?

[1] Except open additional bug reports with Apple so they fix the PATH handling for GUI apps.

**Comment by ironcladlou** [comment]
Very interesting. I actually developed the PATH lookup stuff to find `go` using OSX 10.10.3. I updated to 10.10.4 yesterday, and sure enough, loading Sublime right now, I can reproduce this error.

Thanks for the report. It's definitely a 10.10.4 regression. I'll see what I can figure out!

**Comment by ironcladlou** [comment]
Worse case I could introduce a go installation path setting, and try providing an OSX specific GoTools preferences file which defaults it to include /usr/local/bin (which is probably safe to assume is going to cover most people).

**Comment by ironcladlou** [comment]
@ottob an easier workaround in the meantime might be to symlink `/usr/local/bin/go -> /usr/bin/go`.

**Comment by ironcladlou** [comment]
Fixed (hopefully) in version 0.1.2.

**Comment by ironcladlou** [comment]
@ottob GoTools 0.1.3 just landed in Package Control. Would you mind upgrading and verifying the fix? If the upgrade doesn't fix it, please re-open this issue. Thanks again!

**Comment by ironcladlou** [comment]
I verified an upgrade from 0.1.1 to 0.1.3 on my MacBook running OSX 10.10.4.

**Comment by ottob** [comment]
Yes, works here too. Thanks!
