### ISSUE TITLE
Goto Definition improvement

### ISSUE THREAD

**Issue by ottob** [ironcladlou/GoTools#76]
Right now it only seems to work for code within the current project. I can't "Goto Definition" to something in the stdlib (for instance `fmt.Sprintf()`[1]) or GOPATH (for example `rollbar.Error()`[2]).

When I right click any of the methods mentioned above, no "Goto Definition" action is available. I've tried with both the oracle and godef backends.

Both of these scenarios work with https://github.com/joefitzgerald/go-plus [3] and GoSublime. So it would be really nice if this could be implemented in GoTools as well.

[1] located in `/usr/local/Cellar/go/1.4.2/libexec/src/fmt/print.go` on my computer.
[2] located in `$GOPATH/src/github.com/stvp/rollbar/rollbar.go`
[3] after https://github.com/joefitzgerald/go-plus/pull/210 was merged.

**Comment by ironcladlou** [comment]
@ottob 

Just to be sure there's not a UX/documentation mismatch here. You said:

> I can't "Goto Definition" 
> ...
>When I right click any of the methods mentioned above, no "Goto Definition" action is available.

These statements lead me to believe you're referring to Sublime's built-in `goto_definition` command. GoTools implements go to definition for Go source with a custom `gotools_goto_def` command, [documented here](https://github.com/ironcladlou/GoTools#go-to-definition).

If you position your cursor on one of those symbols and use "GoTools: Go to definition" from the command palette, what happens?

**Comment by ottob** [comment]
With the "GoTools: Go to definition" command it works. Sorry for the noise! :)

**Comment by ironcladlou** [comment]
No problem! I wonder if GoTools should somehow integrate with the built-in command.

**Comment by ottob** [comment]
Btw, do you know if there is any difference in practice between using oracle or godef? Some pros/cons in the documentation might be helpful.

**Comment by stevekuznetsov** [comment]
It's much less of a cold cut divide between the two than you might think.
I've been trying to keep tabs on edge case issues I find but even those
change with tool versions.

I've found one issue with Oracle - it doesn't work (well?) In isolated code
areas - tests, etc. Then again, some people's vi-go setups that use Oracle
don't have that issue so it may be an implementation thing.

Oracle was not able to find the definition of an embedded type today, while
GoDef was. I think the best move might be to try both if one fails and then
the user choice is which to prefer.

**Comment by ottob** [comment]
@stevekuznetsov thanks, that makes sense.
