### ISSUE TITLE
Add support for gorename

### ISSUE THREAD

**Issue by cbednarski** [ironcladlou/GoTools#91]
Got GoTools installed with painless setup. Thanks!

I'm curious if you have plans to add support for `gorename`, or if you'd accept a PR for this.

**Comment by stevekuznetsov** [comment]
PRs are welcome!

Have you had a positive experience with `gorename`? I remember it not
working as expected when @ironcladlou and I looked at it earlier.

**Comment by cbednarski** [comment]
It's flaky. It doesn't work at all if you have compile errors. But it works often enough to save a lot of time.

**Comment by ironcladlou** [comment]
I personally don't use it and so don't have many ideas yet for how it could be integrated into Sublime. As @stevekuznetsov said, PRs are certainly welcome. @cbednarski, did you already have some vision of what a `gorename` integration might look? Can you elaborate on the flakiness? I don't remember much about @stevekuznetsov and I's experiments and since I don't use it day to day I can't assess the annoyance level.

**Comment by cbednarski** [comment]
> @cbednarski, did you already have some vision of what a gorename integration might look?

I started looking at this today. I think it looks pretty similar to the oracle code, but with an input prompt for the new symbol name.

> Can you elaborate on the flakiness? I don't remember much about @stevekuznetsov and I's experiments and since I don't use it day to day I can't assess the annoyance level.

gorename uses go's AST and parser to rewrite the file with the new symbol name, so if the source syntax is invalid gorename doesn't work (compared to e.g. IntelliJ which is a bit more flexible).

I've also seen gorename fail on valid code before but it's not that common.

**Comment by ullutau** [comment]
+1

**Comment by cbednarski** [comment]
I've implemented this [here](https://github.com/ironcladlou/GoTools/compare/master...cbednarski:f-rename) but I'm getting this error when I run the rename command in Sublime. The same command works on the CLI so I suspect it has something to do with the execution environment, but I don't exactly how to fix it.

```
GoTools: spawning process:
GoTools: GOPATH=/Users/cbednarski/code/golang
GoTools: /Users/cbednarski/code/golang/bin/gorename -offset /Users/cbednarski/code/golang/src/github.com/cbednarski/putbin/datastore.go:#164 -to Pie
GoTools: process returned (1) in 0 seconds
GoTools: stderr:
cgo failed: [go tool cgo -objdir /var/folders/mt/q5nyhg2x4hvg77ycy189g3g80000gn/T/net_C170685280 -- -I /var/folders/mt/q5nyhg2x4hvg77ycy189g3g80000gn/T/net_C170685280 cgo_bsd.go cgo_unix.go]: exec: "go": executable file not found in $PATH
cgo failed: [go tool cgo -objdir /var/folders/mt/q5nyhg2x4hvg77ycy189g3g80000gn/T/crypto_x509_C511967039 -- -I /var/folders/mt/q5nyhg2x4hvg77ycy189g3g80000gn/T/crypto_x509_C511967039 -mmacosx-version-min=10.6 -D__MAC_OS_X_VERSION_MAX_ALLOWED=1060 root_cgo_darwin.go]: exec: "go": executable file not found in $PATH
gorename: couldn't load packages due to errors: net, crypto/x509
```

It looks like `gorename` can't find `go`. Since this is likely only an OSX problem I might be able to hack the path for OSX (`env["PATH"]` didn't seem to help, though). I haven't tested on Linux / Windows yet.

**Comment by ironcladlou** [comment]
Thanks for helping with this.

PATH in Sublime with OSX is apparently often busted lately (at least as of 10.10.4). I have [a hack](https://github.com/ironcladlou/GoTools/commit/34533d0194280709c4afb6f49d105c1f2dfe2c7b) which is intended to fix it, but only for GoTools' internal resolution of the `go` binary. The PATH resolved during plugin init isn't stored for use and isn't passed through to the tool execution environment by `ToolRunner`.

You might have to start storing the PATH resolved during init in `GoToolsSettings`. See https://github.com/ironcladlou/GoTools/blob/master/gotools_settings.py for details.

I might have time later tonight to take a closer look. I'm curious to think about how it would be possible to report what `gorename` did other than silently rewriting a bunch of files.

**Comment by ironcladlou** [comment]
I forgot to add: once you start capturing PATH somewhere accessible by plugins, you'd need to modify `ToolRunner` to pass through the corrected PATH from settings.

**Comment by cbednarski** [comment]
> I forgot to add: once you start capturing PATH somewhere accessible by plugins, you'd need to modify ToolRunner to pass through the corrected PATH from settings.

Oops. I implemented something else before I saw your comments. If you don't like [the approach I took](https://github.com/ironcladlou/GoTools/pull/92) I can adjust it.

> I might have time later tonight to take a closer look. I'm curious to think about how it would be possible to report what gorename did other than silently rewriting a bunch of files.

Yeah I thought about this briefly. I think we could use something similar to the find window to show the output from the rename command.
