### ISSUE TITLE
Formatting Issues

### ISSUE THREAD

**Issue by stevekuznetsov** [ironcladlou/GoTools#93]
Somehow the new combination of `goimports` + `gofmt` is not using the correct indentation. but only for [this one file](https://github.com/stevekuznetsov/origin/commit/74c436cbc098c4c74993a6a20e9c9d0c9ca0eb78#diff-82b177f33340bafc51afeea585dc1a58).

**Comment by stevekuznetsov** [comment]
I had somehow managed to change that specific file's tab width to 2 instead of 4. Unclear how. Regardless, [Effective Go](http://golang.org/doc/effective_go.html#formatting) says that `gofmt` will always use tabs and never spaces, so Sublime Text is converting the tabs into spaces at some point? Perhaps this should not be allowed behavior.

**Comment by stevekuznetsov** [comment]
@pmorie Ridicule accepted for this amazing display of ineptitude.

**Comment by ironcladlou** [comment]
@stevekuznetsov 
>so Sublime Text is converting the tabs into spaces at some point and perhaps this should not be allowed behavior. Is this something that GoTools can over-ride?

I thought this would take care of it: https://github.com/ironcladlou/GoTools/blob/master/GoTools.sublime-settings#L26

But of course, assuming that still works (assigning a global setting from the plugin), user settings will always take precedence.

**Comment by ironcladlou** [comment]
Going to close this one since I don't think there's anything more the plugin can do about it.
