### ISSUE TITLE
AttributeError when trying to use pretty much any command (OS X, Go 1.5)

### ISSUE THREAD

**Issue by ferbivore** [ironcladlou/GoTools#94]
I get this when trying to run the "GoTools: Format" command from the palette:

    Traceback (most recent call last):
      File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 556, in run_
        return self.run(edit)
      File "gotools_format in /Users/Andy/Library/Application Support/Sublime Text 3/Installed Packages/GoTools.sublime-package", line 26, in run
      File "gotools_settings in /Users/Andy/Library/Application Support/Sublime Text 3/Installed Packages/GoTools.sublime-package", line 19, in __init__
    AttributeError: 'GoToolsSettings' object has no attribute 'GoEnv'

And the same thing every time I save a Go file:

    Traceback (most recent call last):
     File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 240, in on_pre_save
       callback.on_pre_save(v)
     File "gotools_format in /Users/Andy/Library/Application Support/Sublime Text 3/Installed Packages/GoTools.sublime-package", line 15, in on_pre_save
     File "gotools_settings in /Users/Andy/Library/Application Support/Sublime Text 3/Installed Packages/GoTools.sublime-package", line 19, in __init__
    AttributeError: 'GoToolsSettings' object has no attribute 'GoEnv'

I get identical errors when trying to use any oracle-related command. And `Unable to find target command: gotools_build` when trying to build. This happens both with an empty user preferences file and if I specify the gopath and goroot settings manually. What should I try next?

It might be worth noting that formatting doesn't work with GoSublime either, for some reason, but it doesn't show any errors - it just silently fails.

**Comment by tamird** [comment]
This is because your sublime text is running without GOPATH in its environment.

**Comment by ferbivore** [comment]
```python
>>> import os
>>> os.environ["GOPATH"]
'/Users/Ferb/Documents/Go'
```

**Comment by tamird** [comment]
can you restart sublime and open the console? there should be some useful output in there

**Comment by ferbivore** [comment]
Gist: https://gist.github.com/ferbivore/0b42552011eba0d0ecc0. The relevant part is this:

    Exception: GoTools: couldn't find the go binary in PATH: /Users/Ferb/Scripts /Users/Ferb/Documents/Go/1.5/bin /Users/Ferb/Documents/Go/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /opt/X11/bin /Library/TeX/texbin

It's quite odd. `/Users/Ferb/Documents/Go/1.5/bin` is my `GOROOT`, and indeed the `go` binary is there.

You may have a point though - I just noticed GOPATH, GOROOT and the correct PATH are only in Sublime's environment if I start it using the `subl` command. I get the exact same error whether or not I do that, though, which is a bit odd.

**Comment by ironcladlou** [comment]
@ferbivore What version of OSX are you using? This sounds similar to #73 which I tried to resolve via #74. GoTools simply can't find `go` on your PATH. I've been avoiding adding a PATH setting  and would prefer to close any auto-detection gaps if possible.

There's something nagging me about your console output, which I assume is copy/pasted verbatim:

```
Exception: GoTools: couldn't find the go binary in PATH: /Users/Ferb/Scripts /Users/Ferb/Documents/Go/1.5/bin /Users/Ferb/Documents/Go/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /opt/X11/bin /Library/TeX/texbin
```

That particular logging output on Darwin is the result of this command:

```python
command = "/usr/bin/login -fqpl $USER $SHELL -l -c 'printf \"%s\" \"$PATH\"'"
```

Notice the lack of path separators in your output? When scanning PATH, I split on `os.pathsep` which is `:` on Darwin. If your PATH returned from that command is actually a space-separated string of paths, nothing will ever be found.

Would you be willing to use the Sublime console to try and replicate [this function](https://github.com/ironcladlou/GoTools/blob/master/gotools_settings.py#L72) and see what output you get?

An an aside, I need a better way for GoTools to inform the user when the plugin fails to initialize. Any suggestions?

**Comment by ferbivore** [comment]
You're right, it was the path separators. I use [fish](http://fishshell.com/) as my shell, and it uses spaces to separate path entries - changing it back to bash is the quick fix.

However, there is a slightly ridiculous (if conceptually simple) solution:

```python
>>> command = '/usr/bin/login -fqpl $USER $SHELL -l -c \'sh -c "printf %s \$PATH"\''
>>> stdout, stderr = subprocess.Popen(command, stdout=subprocess.PIPE, shell=True).communicate()
>>> stdout.decode()
'/Users/Ferb/Scripts:/Users/Ferb/Documents/Go/1.5/bin:/Users/Ferb/Documents/Go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:'
```

I can't test this extensively today (it might require more quoting for paths with spaces - fish doesn't seem to support this concept at all, oddly enough), but it seems to work for both fish and bash.

**Comment by ironcladlou** [comment]
Calling `sh` from $SHELL... *slowclap* :clap:

It's just crazy enough to work! I'll give this a try later on my MacBook (using bash).

**Comment by ironcladlou** [comment]
Created #97 to track the underlying bug.

**Comment by evgenybf** [comment]
btw, the same issue exists on windows as well:

```
reloading Packages/User/Package Control.sublime-settings
Package Control: No updated packages
Traceback (most recent call last):
  File "C:\Apps\sublime3\sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "gotools_goto_def in C:\Apps\sublime3\Data\Installed Packages\GoTools.sublime-package", line 21, in run
  File "gotools_settings in C:\Apps\sublime3\Data\Installed Packages\GoTools.sublime-package", line 19, in __init__
AttributeError: 'GoToolsSettings' object has no attribute 'GoEnv'
>>> import os
>>> os.environ['GOPATH']
'C:\\Develop\\Go\\gopath'
```

**Comment by ferbivore** [comment]
You should probably file a new bug; I'm not sure this is the same underlying problem.
