### ISSUE TITLE
Using Fish shell on OSX breaks plugin initialization

### ISSUE THREAD

**Issue by ironcladlou** [ironcladlou/GoTools#97]
The OSX PATH fix (#74) assumes the user's login shell is Bash. If the user's shell is Fish, the PATH interpreting will fail because the output from `printf` will be shell specific and may not be formatted predictably (e.g. separated by `os.pathsep`). This can prevent GoTools from locating the `go` binary and basically breaks the plugin.

@ferbivore proposed a fix (https://github.com/ironcladlou/GoTools/issues/94#issuecomment-138706827) which invokes `sh` from the user's shell, which seems workable.

**Comment by ferbivore** [comment]
We seem to keep similar hours - I was just testing out an alternative. This seems much less unwieldy than what you're currently using (and what I proposed):

```python
>>> import subprocess, os
>>> subprocess.check_output([os.getenv("SHELL"), "-c", "sh -c 'echo $PATH'"]).decode("utf-8").rstrip()
'/Users/Ferb/Scripts:/Users/Ferb/Documents/Go/1.5/bin:/Users/Ferb/Documents/Go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:'
```

Two assumptions: one, the `/usr/bin/login` trick isn't actually useful (it isn't for fish - I haven't tested bash as a system shell yet, and SublimeFixMacPath's [source](https://github.com/int3h/SublimeFixMacPath/blob/master/FixPath.py) doesn't mention the _reason_ for using it), and two, the only reason you were using `printf` was to get rid of the newline. The command itself, I've tested with everything on my system - fish, bash, zsh, ksh, they all print their respective PATHs just fine.

**Comment by ironcladlou** [comment]
Awesome research, thanks. I was in a hurry for an OSX PATH fix after my initial release to Package Control and didn't spend a lot of time understanding the implementation from SublimeFixMacPath. I should have a little time later tonight to go over my GoTools backlog, and I'll see if I can get your fix merged to master (unless you plan on making a PR).

**Comment by ferbivore** [comment]
I'm working on a pull request, it should be up in a few minutes if everything goes okay.

**Comment by ferbivore** [comment]
I did run into another issue, namely that `go env` seems to think my GOROOT is `/usr/local/go` for some reason:

```python
>>> p = subprocess.Popen(["/Users/Ferb/Documents/Go/1.5/bin/go", "env"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
>>> p.communicate()
(b'', b'go: cannot find GOROOT directory: /usr/local/go\n')
```

**Comment by ferbivore** [comment]
Pull request: https://github.com/ironcladlou/GoTools/pull/98
